### ISSUE TITLE
Penalized likelihood

### ISSUE THREAD

**Issue by ziyimo** [ziyimo/circ-immu#1]
### Premise

Previously we've established that the binomial probability for testing positive $q$ is calculated by  $q = \frac{p}{\pi}$, where $p$ is the model prediction of the infection rate in the general population, and $\pi$ is the proportion of influenza-like illness (ILI) visits in the hospital (proxy for "testing rate").

The issue arises when we have a model (during optimization) where it predicts $p > \pi$ for particular data points, which reflects potential violations to our modeling assumption. We introduced a fudge factor $c \in (0, 1]$ that scales down the calculation of $q$ by $q = c \times \frac{p}{\pi}$.

The lingering issues are that:
1. We don't have a particularly good idea of how to pick $c$ given the data. External estimates of infection rates circles back to the exact dataset we are working with.
2. Even with the most stringent choice of $c$, during the optimization phase, there will still be some model proposed in the parameter space that predicts very high $p$ where it exceeds $\pi$ in the data. So far, we have been employing a _capping_ strategy where, for the purpose of calculating the binomial likelihood, we cap the value of the binomial probability $q$ by a threshold $q_{cap}$, calculated from data:
``` R
q_99 <- binom.confint(k[!missing], TT[!missing], conf.level = 0.99, methods = c("exact"))
q_99cap <- max(q_99$upper)
```
$q_{cap}$ here is calculated as the maximum value of the upper 99% confidence interval of the binomial probability calculated from observed data (positive tests `k` and total tests `TT`, see fig. 1 for illustration). The confidence level here can be adjusted (increased).
In summary, the binomial probability $q'$ is calculated from the model prediction as follows:
$$ q = c \times \frac{p}{\pi} $$
$$ q' = \min{(q, q_{cap})} $$

3. The "naïve" _capping_ strategy seems not to be penalizing the models that have huge peaks enough, as it essentially "flattens out" the peaks. This can be seen by this following example of model fit:
<img src="https://user-images.githubusercontent.com/19890895/99564690-5f8c6d00-2990-11eb-8c39-3d45993fff7c.png" width=500 align=center>
Note that the fitted model gets the shape of the lower part of the dataset well, at the expense of producing big peaks.

### Proposed solution

To explicitly penalize the model for exceeding the cap, we propose to introduce a penalization term to the negative log likelihood function. The penalization term kicks in only when the model predicted $q > q_{cap}$, and it scales linearly (maybe we can also try quadratic?) to how much the model prediction exceeds $q_{cap}$ by a hyperparameter $\lambda$. So given that $q' = \min{(q, q_{cap})}$, the penalized negative log likelihood of an observation is calculated by
$$-\log{\mathcal{L}_{pnl}(q; k, T)} = -\log{\mathcal{L}(q'; k, T)} +  \lambda(q-q') = -\log{\Pr(k | q', T)} + \lambda(q-q') $$

The following figure illustrates how the penalized likelihood function works:
![Rplot](https://user-images.githubusercontent.com/19890895/99557086-e6891780-2987-11eb-8ce4-b06e55cb21bb.png)
__Fig 1. Example of a dataset we are fitting to: Positivity rate (blue) with 99% confidence interval of the binomial probability, proportion of ILI visits (red) and estimator for infection rate in the general population (orange) for influenza cases in NY state__

We will try to set the $\lambda$ parameter empirically so that in the end the model is penalized at no more than just a handful of data points.

__On the issue of `c`__

We will treat `c` as a parameter to be optimized in the model, in hopes of the data being actually informative of `c`. The reasoning goes as follows:

There are two main features of the SIRS model we are fitting -- the shape/periodicity and amplitude. The fact of the matter is, we do not have a good idea of the ground truth amplitude (i.e. struggling to figure out a reasonable value of `c` _a priori_). So if the data is _not_ informative of the amplitude, then we have a problem to conduct this model comparison study based on Maximum Likelihood, since the amplitude aspect would confound any model comparison.

**Comment by asiepel** [comment]
really nice summary of our conversation!

**Comment by asiepel** [comment]
often a tuning parameter such as $\lambda$ can be set by cross validation, but I'm not sure how do that in this setting -- unless you write a simple simulator and test the method on simulated data....?
