### ISSUE TITLE
Choosing models of $R_0$, and the geographic variations of commute time

### ISSUE THREAD

**Issue by ziyimo** [ziyimo/circ-immu#2]
#### The SIRS model

The SIRS model is a system of differential equations that governs the epidemiological dynamics of a population. The variables specifying the transmission dynamics in a population are the number of 1) susceptible ($S$),  2) infected ($I$), and 3) recovered ($R$) people in the population, and the SIRS model is as follows:
$$ \frac{dS}{dt} = \frac{R}{L} - \frac{\beta(t) IS}{N}$$
$$ \frac{dI}{dt} =  \frac{\beta(t) IS}{N} -\frac{I}{D} $$
Given that the total population ($N$) remains constant (i.e. $\frac{dN}{dt} = 0$) and $N = S+I+R$, it follows that
$$ \frac{dR}{dt} = \frac{I}{D} - \frac{R}{L}$$

We treat $D$ the mean infection period and $L$ the duration of immunity as known for a certain disease (e.g. we use $D=5 \ \mathrm{days}$ and $L= 40\times 7 \ \mathrm{days}$ for flu). __And therefore the centerpiece that governs the transmission dynamics is $R_0$, which plugs in to the model through $R_0(t) = \beta(t)D$__

#### Running the SIRS model

Given a particular pattern of annual change in $R_0$ (discussed below), we run the SIRS model as follows

* We start with $ S= N-1, I=1, R=0 $, where $N$ is set to be the census population of a particular state.
* We run the system of differential equations for 50 years.
* Empirically, we observe that regardless of which day of the year the model is initialized, given the annual cyclical pattern of $R_0$, the model converges to a steady annual cycle after running it long enough.
* If $R_0$ is constant, the system converges to a steady state.
* The model predicts daily $p = \frac{I}{N}$, which is what we use to fit the data (see the _Penalizd likelihood_ thread)

#### Modelling $R_0$

Some notations for this section:
* $R_{0, min}$: minimum $R_0$, we use 1.2 for flu
* $R_{0, max}$: maximum $R_0$, we use 2 for flu
* $h(t)$: specific humidity on day $t$
* $s(t)$: time of sunrise on day $t$

The flexibility of the SIRS model lies in how we model the annual change of $R_0$, here we consider the following options

__1. Constant $R_0$ throughout (null model)__

This can be the baseline model for our BIC comparison. As mentioned above, this leads to a constant infection rate in the population. When fitting jointly to multiple state, we can give each state its own $R_0$ maybe?

__2. $R_0$ depending on humidity through an exponential decay (_Baker et al._ model)__

<img src="https://user-images.githubusercontent.com/19890895/100127150-6f022f00-2e44-11eb-96f4-a5908f0f4c0e.png" width=380 align="center"> $ R_0(t) = e^{\alpha h(t)}(R_{0, max}-R_{0, min})+R_{0, min} $ 

Here a single parameter $\alpha$ governs how fast $R_0$ decays with humidity increasing. 

__3. $R_0$ depending on a single underlying variable (sunrise time or humidity) through a logistic function__

$$ R_0(t) =  \frac{R_{0, max}-R_{0, min}}{1+e^{-ks(t)+b}}+R_{0, min} \ \ \ \ \ R_0(t) =  \frac{R_{0, max}-R_{0, min}}{1+e^{-kh(t)+b}}+R_{0, min} $$
<img src="https://user-images.githubusercontent.com/19890895/100130035-dd94bc00-2e47-11eb-9422-9549c2fa9d2b.png" width=380 align=center> <img src="https://user-images.githubusercontent.com/19890895/100130045-dff71600-2e47-11eb-9fd8-235cb855643e.png" width=380 align=center>

As we've discussed before, the motivation for choosing a logistic model (particularly for sunrise time) is that it gives us an explicit control over the _dynamic range_ of a window where $R_0$ responds most strongly to change in the underlying variable. The aspect of "saturation" we've been discussing in the channel is another way to look at it.

What the logistic model __cannot__ do is to capture the potential decay in $R_0$ once sunrise is so late (what Rob pointed out might have been happening in Scandinavian countries). For that we may need a bell-shaped model. But at least in our flu data, we don't have extreme cases like that (maybe Alaska, but the data there is quite incomplete and we will most likely toss it out in our final analysis).

Coming back to the logistic model. It has two parameters, $k$ and $b$. The $k$ parameter controls how steep the curve looks, and the $b$ ("intercept") parameter is somewhat of a nebulous idea. It controls the center/dynamic range of the curve __in conjunction with__ $k$. So conditioned on a value of $k$, the center of the curve $s_0$, $h_0$ (i.e. halfway point between $R_{0, max}$ and $R_{0, min}$) is at $s_0, h_0=\frac{b}{k}$. Note that originally the model was parameterized explicitly with $s_0$ or $h_0$, which led to coupling between the intercept and $k$.

__4. $R_0$ depending on the linear combination of two underlying variables (sunrise time and humidity) through a logistic function__

<img src="https://user-images.githubusercontent.com/19890895/100130851-e89c1c00-2e48-11eb-9b9b-21dea0e9b6d5.png" width=380 align=center> $ R_0(t) =  \frac{R_{0, max}-R_{0, min}}{1+e^{-k_1s(t)-k_2h(t)+b}}+R_{0, min} $ 

Currently we combine sunrise and climate variables linearly with coefficients $k_1$ and $k_2$, and intercept $b$, and then use a logistic link function to produce $R_0$. Here, $k_1$ and $k_2$ determine how steep the response is in the direction of each variable, and $b$ defines a line in the sunrise-humidity space $k_1s+k_2h=b$ where $R_0$ is halfway between $R_{0, max}$ and $R_{0, min}$.

#### Choosing $R_0$ models

As touched upon above, we need to make some decisions about what exact $R_0$ model to use to fit each variable. From what we were discussing in the channel, the issues seem to boil down to justifying the switch from the __exponential__ humidity model to __logistic__. We have established that:
* It's better to do model comparison b/n the same functional form
* Logistic somewhat generalizes the exponential

To be discussed/tested:
* Does logistic fit strictly better than exponential (for climate data)? We want to make sure that we are not misspecifying the model for climate data by using logistic.

#### Jointly fitting to multiple states & epidemiological interpretation of the "intercept"

We would like to fit a single $R_0$ model jointly to data from multiple states. It makes sense to have the same $k$ for all states, since we interpret that as the _dependency_ of $R_0$ on sunrise/humidity and given the underlying physiological mechanism this should not vary from state to state. We need to decide whether we want to use the same $b$ for all states.
* The argument for having a free parameter $b$ for each state is that we interpret it as representing the "window of vulnerability", and since commute times can vary between states/locales, we expect this window to be different. 
* However, having a free $b$ for each state would blow up the parameter space and may cause optimization issues.

**Comment by ziyimo** [comment]
### Meeting minutes (Nov 25)

__Flu epidemiological model__
* "Centered" double exponential for sunrise time to "mimic" bell curve. This is for easy integration with the Baker et al. climate model.
* Run both Gaussian and double exponential for sunrise.
* Try both having a single "peak"/commute time for all states and having unique one for each state

**Comment by ziyimo** [comment]
### Options for modeling $R_0$ dependence on sunrise

We have established that the function form of $R_0$ dependence on sunrise should really have a __peak__ around commute time, given the underlying physiological mechanism.

__Double exponential__

$$ R_0(t) = e^{\alpha \left| s(t)-s_0 \right| }(R_{0, max}-R_{0, min})+R_{0, min} $$

<p align="center"> <img src="https://user-images.githubusercontent.com/19890895/100643676-fb5a9900-32ff-11eb-8000-de5a14176a28.png" width=450> </p>

where $\alpha \leq 0$ is the rate of decay, and $s_0 \in (0, 1)$ is the center of the peak.

__Gaussian__

$$ R_0(t) = e^{-\frac{(s(t)- \mu)^2}{2\sigma^2}}(R_{0, max}-R_{0, min})+R_{0, min} $$

<p align="center"> <img src="https://user-images.githubusercontent.com/19890895/100644135-89cf1a80-3300-11eb-8be9-819629e3d31d.png" width=450> </p>

where $\sigma^2 > 0$ is the "variance" and $\mu \in (0, 1)$ is the "mean". 

Alternatively, we can parameterize with $\alpha = -\frac{1}{2\sigma^2} \leq 0$ as the rate of decay, and $s_0 = \mu$ as the center of the peak.

### Options to combine sunrise and humidity models

__1. Linearly combine exponential terms__

$$ R_0(t) = e^{\alpha_1 \left| s(t)-s_0 \right| + \alpha_2 h(t)}(R_{0, max}-R_{0, min})+R_{0, min} $$

This is the "hack" we discussed during the Nov 25 meeting.

$$\alpha_1 = -10, s_0 = 0.5, \alpha_2 = -50$$
<p align="center"> <img src="https://user-images.githubusercontent.com/19890895/100775285-ae8ec500-33c8-11eb-937b-a39e06359a18.png" width=300> </p>

__2. Model as convex mixture of Gaussian (sunrise) and exponential (humidity)__

$$ R_0(t) = \left[ \rho e^{-\frac{(s(t)- \mu)^2}{2\sigma^2}} + (1-\rho)e^{\alpha h(t)} \right](R_{0, max}-R_{0, min})+R_{0, min}   $$

This is the solution Adam sketched out in the Slack channel. With the $\pi$ parameter replaced with the symbol $\rho$ (since we use $\pi$ for "testing rate"). The issue as Adam pointed out is when $\rho$ is close to 0 or 1, there is an identifiability issue with other model parameters!

$$\alpha_1 = -10, s_0 = 0.5, \alpha_2 = -50, \rho = 0.75 \ \ \ \ \alpha_1 = -10, s_0 = 0.5, \alpha_2 = -50, \rho = 0.25$$
<p align="center"> <img src="https://user-images.githubusercontent.com/19890895/100775609-1e9d4b00-33c9-11eb-8fb7-b64e1402f900.png" height=300> <img src="https://user-images.githubusercontent.com/19890895/100775665-307eee00-33c9-11eb-9920-5e2d1de0be9e.png" height=300>
 </p>


__3. Linearly combine Gaussian and exponential terms (?)__

$$ R_0(t) = e^{\alpha_1 (s(t)-s_0)^2 + \alpha_2 h(t)}(R_{0, max}-R_{0, min})+R_{0, min} $$

Using the parameterization $\alpha = -\frac{1}{2\sigma^2}$ and $s_0 = \mu$ for the Gaussian model, we can write $R_0(t) = e^{\alpha(s(t)- s_0)^2}(R_{0, max}-R_{0, min})+R_{0, min}$. This essentially looks like the double exponential with a squared exponential term. Similar to strategy 1, we can linearly combine this squared term with the humidity term in the exponent. Is this something mathematically sound?

$$\alpha_1 = -10, s_0 = 0.5, \alpha_2 = -50$$
<p align="center"> <img src="https://user-images.githubusercontent.com/19890895/100775536-05949a00-33c9-11eb-8270-4d26e0efc526.png" width=300> </p>

**Comment by asiepel** [comment]
yes, option #3 is interesting too.  I wonder, though, do you want an intercept term as well for the linear combination solutions?  Not sure.   Can justify not including it from first principles but on the other hand, it would give you an additional degree of freedom for fitting.  Note that it acts like a scale factor, since the exp of a sum is equal to the product of the exps.

**Comment by ziyimo** [comment]
> yes, option #3 is interesting too. I wonder, though, do you want an intercept term as well for the linear combination solutions? Not sure. Can justify not including it from first principles but on the other hand, it would give you an additional degree of freedom for fitting. Note that it acts like a scale factor, since the exp of a sum is equal to the product of the exps.

So by multiplying the exponential to $(R_{0, max}-R_{0, min})$, the "intercept" term for options 1 & 3 is essentially fixed to $\log{(R_{0, max}-R_{0, min})}$, and this is to ensure that the resulting $R_0(t)$ values are strictly between $R_{0, max}$ and $R_{0, min}$. I am not sure what removing this constraint entails.

**Comment by asiepel** [comment]
hmm, yes may be a problem there.  The exp terms as you have them are not guaranteed to be $\leq 1$.

**Comment by ziyimo** [comment]
> hmm, yes may be a problem there. The exp terms as you have them are not guaranteed to be ≤1.

In the case of sunrise, $\alpha_1$ is a reparametrization of $-\frac{1}{2\sigma^2}$ and therefore $<0$. For humidity, $h(t) \geq 0$, and _a priori_ we constrain $\alpha_2 \leq 0$ (as in Baker et al.) since we expect $R_0$ to fall with increasing humidity. So in the end both $\alpha_1 \left| s(t)-s_0 \right| + \alpha_2 h(t)$ and $\alpha_1 (s(t)-s_0)^2 + \alpha_2 h(t)$ terms should be guaranteed $\leq 0$, and therefore the exponential terms $\leq 1$.

**Comment by asiepel** [comment]
ah yes, ok

**Comment by ziyimo** [comment]
> ### Options for modeling R0 dependence on sunrise
> We have established that the function form of R0 dependence on sunrise should really have a **peak** around commute time, given the underlying physiological mechanism.
> 
> **Double exponential**
> 
> R0(t)=eα|s(t)−s0|(R0,max−R0,min)+R0,min
> <img alt="" width="450" src="https://user-images.githubusercontent.com/19890895/100643676-fb5a9900-32ff-11eb-8000-de5a14176a28.png">
> 
> where α≤0 is the rate of decay, and s0∈(0,1) is the center of the peak.
> 
> **Gaussian**
> 
> R0(t)=e−(s(t)−μ)22σ2(R0,max−R0,min)+R0,min
> <img alt="" width="450" src="https://user-images.githubusercontent.com/19890895/100644135-89cf1a80-3300-11eb-8be9-819629e3d31d.png">
> 
> where σ2>0 is the "variance" and μ∈(0,1) is the "mean".
> 
> Alternatively, we can parameterize with α=−12σ2≤0 as the rate of decay, and s0=μ as the center of the peak.
> 
> ### Options to combine sunrise and humidity models
> **1. Linearly combine exponential terms**
> 
> R0(t)=eα1|s(t)−s0|+α2h(t)(R0,max−R0,min)+R0,min
> This is the "hack" we discussed during the Nov 25 meeting.
> 
> α1=−10,s0=0.5,α2=−50
> <img alt="" width="300" src="https://user-images.githubusercontent.com/19890895/100775285-ae8ec500-33c8-11eb-937b-a39e06359a18.png">
> 
> **2. Model as convex mixture of Gaussian (sunrise) and exponential (humidity)**
> 
> R0(t)=[ρe−(s(t)−μ)22σ2+(1−ρ)eαh(t)](R0,max−R0,min)+R0,min
> This is the solution Adam sketched out in the Slack channel. With the π parameter replaced with the symbol ρ (since we use π for "testing rate"). The issue as Adam pointed out is when ρ is close to 0 or 1, there is an identifiability issue with other model parameters!
> 
> α1=−10,s0=0.5,α2=−50,ρ=0.75    α1=−10,s0=0.5,α2=−50,ρ=0.25
> <img alt="" height="300" src="https://user-images.githubusercontent.com/19890895/100775609-1e9d4b00-33c9-11eb-8fb7-b64e1402f900.png"> <img alt="" height="300" src="https://user-images.githubusercontent.com/19890895/100775665-307eee00-33c9-11eb-9920-5e2d1de0be9e.png">
> 
> **3. Linearly combine Gaussian and exponential terms (?)**
> 
> R0(t)=eα1(s(t)−s0)2+α2h(t)(R0,max−R0,min)+R0,min
> Using the parameterization α=−12σ2 and s0=μ for the Gaussian model, we can write R0(t)=eα(s(t)−s0)2(R0,max−R0,min)+R0,min. This essentially looks like the double exponential with a squared exponential term. Similar to strategy 1, we can linearly combine this squared term with the humidity term in the exponent. Is this something mathematically sound?
> 
> α1=−10,s0=0.5,α2=−50
> <img alt="" width="300" src="https://user-images.githubusercontent.com/19890895/100775536-05949a00-33c9-11eb-8270-4d26e0efc526.png">

So for the paper, we can have a narrative along the following lines:

* Based on physiological mechanism, we expect "peaks" in the $R_0$ model, so we fit "double-exponential" and Gaussian $R_0$ sunrise model jointly to all states, allowing each state to have its own $s_0$ ("peak").

* Based on what we observed so far, and what we discussed today about how the data is not informative of what the model should look like when sunrise is very late, we should observe that the "peaks" are squashed to the boundary (close to 1/noon).

* And this would justify using a simple exponential model for sunrise with $s_0$ fixed at $1$, allowing for a clean model comparison with humidity (Baker et al.)
